Repository reznok/GMCAbilitySystem, pull requests merged in 2024-03, with the labels that each got.

#31 Dev branch code cleanup (macOS/Linux)
  GMCAbilitySystem.uplugin
  Source/GMCAbilitySystem/Private/Ability/GMCAbility.cpp
  Source/GMCAbilitySystem/Private/Ability/Tasks/SetTargetDataGameplayTag.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
  Source/GMCAbilitySystem/Private/Effects/GMCAbilityEffect.cpp
  Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
  Source/GMCAbilitySystem/Public/Ability/GMCAbilityData.h
  Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataInt.h
  Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataVector3.h
  Source/GMCAbilitySystem/Public/Ability/Tasks/WaitDelay.h
  Source/GMCAbilitySystem/Public/Ability/Tasks/WaitForInputKeyRelease.h
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
  Source/GMCAbilitySystem/Public/GMCAbilitySystem.h
  Source/GMCAbilitySystemTypesInclude/GMCAbilitySystemTypesInclude.Build.cs
Labels: maintenance

#29 Main branch cleanup (macOS, Linux, 'Shipping' configuration)
  GMCAbilitySystem.uplugin
  Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
  Source/GMCAbilitySystemTypesInclude/GMCAbilitySystemTypesInclude.Build.cs
Labels: maintenance

#32 Tag Change Delegates
  GMCAbilitySystem.uplugin
  Source/GMCAbilitySystem/Private/Ability/Tasks/WaitForGameplayTagChange.cpp
  Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
  Source/GMCAbilitySystem/Public/Ability/Tasks/WaitForGameplayTagChange.h
  Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
  Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h
  Source/GMCAbilitySystemEditor/GMCAbilitySystemEditor.Build.cs
  Source/GMCAbilitySystemEditor/Private/GMCAbilitySystemEditor.cpp
  Source/GMCAbilitySystemEditor/Private/Properties/GameplayElementMappingDetails.cpp
  Source/GMCAbilitySystemEditor/Public/GMCAbilitySystemEditor.h
  Source/GMCAbilitySystemEditor/Public/Properties/GameplayElementMappingDetails.h
Labels: enhancement

#34 Add the ability to map attributes to properties as well as tags.
  GMCAbilitySystem.uplugin
  Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
  Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
  Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h
Labels: enhancement

#39 Guard against uninitialized attributes.
  Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
  Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Labels: bug

#41 Add extra accessors for active tags
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Labels: enhancement

#40 Minor cleanup/safety checks.
  Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
  Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Labels: maintenance

#42 Additional animation utility functionality
  Source/GMCAbilitySystem/Private/Actors/GMAS_Pawn.cpp
  Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
  Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
  Source/GMCAbilitySystem/Private/Utility/GMASUtilities.cpp
  Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
  Source/GMCAbilitySystem/Public/Actors/GMAS_Pawn.h
  Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
  Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
  Source/GMCAbilitySystem/Public/Utility/GMASUtilities.h
  Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h
Labels: enhancement

#43 Add helper functions to retrieve input action value in BP easily, add bp function library, etc.
  Source/GMCAbilitySystem/Private/Ability/GMCAbility.cpp
  Source/GMCAbilitySystem/Private/Utility/GMASFunctionLibrary.cpp
  Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
  Source/GMCAbilitySystem/Public/Utility/GMASFunctionLibrary.h
Labels: enhancement
